IF
  Global("EnteredArea","AR5002",0)
THEN
  RESPONSE #100
    ClearAllActions()
    SetGlobal("EnteredArea","AR5002",1)
    CreateCreature("ramaz",[369.616],14)
    StartCutSceneMode()
    StartCutScene("cut225a")
END

IF
  GlobalTimerExpired("reinfg","GLOBAL")
  !Dead("Gromnir")
  Global("EnteredArea","AR5002",1)
THEN
  RESPONSE #100
    SetGlobal("EnteredArea","AR5002",2)
    CreateCreature("grommin",[848.894],6)
    CreateCreature("jumjum",[894.841],6)
END

