IF
  Global("AsylumPlot","GLOBAL",20)
THEN
  RESPONSE #0
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("Cut41g")
END

IF
  AreaCheck("ar1515")
  Global("HostileIn","AR1515",1)
THEN
  RESPONSE #0
    ClearAllActions()
    StartCutSceneMode()
    StartCutScene("Cut41g")
END

IF
  Allegiance(Myself,ENEMY)
  !Global("AsylumPlot","GLOBAL",20)
  GlobalLT("AsylumPlot","GLOBAL",30)
THEN
  RESPONSE #100
    SetGlobal("AsylumPlot","GLOBAL",20)
END

