IF
  HPPercentLT(Myself,50)
  Global("STARTEDCHANGE","LOCALS",0)
THEN
  RESPONSE #100
    StartCutSceneMode()
    ClearAllActions()
    ReallyForceSpellRES("abzaway",Myself)
    Wait(1)
    EndCutSceneMode()
    ReallyForceSpellRES("JWSP02",Myself)
    SetGlobal("STARTEDCHANGE","LOCALS",1)
END

IF
  OR(2)
    Detect([PC])
    See(Player1)
  Global("SelfInit","LOCALS",0)
THEN
  RESPONSE #100
    SetGlobal("SelfInit","LOCALS",1)
    StartDialogNoSet(LastSeenBy(Myself))
END

